### ISSUE TITLE
Scrollbar is not colored

### ISSUE THREAD

**Issue by MercurialPony** [HAHALOSAH/discord_premium_themes#1]
Using BetterDiscord 1.9.0 the scrollbar in text channels is not colored

![image](https://user-images.githubusercontent.com/19710443/227727457-fe30fc63-b8e7-4b1d-b010-9c75d3a9961c.png)

**Comment by HAHALOSAH** [comment]
Thank you for letting me know, I will fix it later today

**Comment by NobleSkye** [comment]
**i made a fix :3**
```css
.theme-dark .customTheme-3QAYZq.auto-2TJ1RH::-webkit-scrollbar-thumb,
.theme-dark .customTheme-3QAYZq.thin-RnSY0a::-webkit-scrollbar-thumb {
    background-color: #00FFFF; /* Neon blue */
}


.theme-light .customTheme-3QAYZq.auto-2TJ1RH::-webkit-scrollbar-thumb,
.theme-light .customTheme-3QAYZq.thin-RnSY0a::-webkit-scrollbar-thumb {
    background-color: #00FFFF; /* Neon blue */
}


.theme-dark .customTheme-3QAYZq.auto-2TJ1RH::-webkit-scrollbar-track,
.theme-dark .customTheme-3QAYZq.thin-RnSY0a::-webkit-scrollbar-track {
    background: linear-gradient(to bottom, #106c74, #18487c); /* Gradient from neon blue to dark blue */
}


.theme-light .customTheme-3QAYZq.auto-2TJ1RH::-webkit-scrollbar-track,
.theme-light .customTheme-3QAYZq.thin-RnSY0a::-webkit-scrollbar-track {
    background: linear-gradient(to bottom, #106c74, #18487c); /* Gradient from neon blue to dark blue */
}
```
this is for **discord_premium_theme.theme.css**

just replace the top. 
it does effect all themes but if you only use chroma it works fine


it does use the actual hex colours from discord so it should match well
